/* eslint-disable @next/next/google-font-display */
/* eslint-disable @next/next/no-page-custom-font */
import { Inter, Geologica, Fira_Code } from 'next/font/google';
import './globals.css';
import { React } from 'react';

const inter = Inter({ subsets: ['latin', 'cyrillic'] })
const geologica = Geologica({ subsets: ['latin', 'cyrillic'] })
const fira_code = Fira_Code({ subsets: ['latin-ext'] })

export const metadata = {
	title: 'slshptt',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	function settings() {
		console.log('cat');
	}
	return (
		<html lang="en">
			<head>
				<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@24,400,0,0" />
			</head>
			<body className={geologica.className}>
				<div id='content'>
					{children}
				</div>
				<header className='fixed w-screen h-12 backdrop-blur-2xl text-center border-b-[1px] border-zinc-800'>
					<div className='h-12 w-screen fixed top-0 flex items-center justify-center'>
						<a className='text-2xl' href='/'>slashhub</a>
					</div>
					<nav className='flex justify-between items-center px-5 h-full w-full'>
						<a className='icon' href='/theotown/plugins' title="slashpotato's projects">deployed_code</a>
						<div className='icon group cursor-pointer'>expand_more
							<div className='hidden group-hover:block hover:block fixed right-0 w-max h-max font-geologica bg-black border-[1px] border-zinc-800 p-1 rounded text-xs' id='qs-list-div'>
								<ul>
									<a href='./settings'><li><i>settings</i>settings</li></a>
									<a href='./profile'><li><i>account_circle</i>profile</li></a>
								</ul>
							</div>
						</div>
					</nav>
				</header>
			</body>
		</html>
	)
}
